// Package handlers contains HTTP controllers, middleware, and routing.
package handlers

import (
	"time"

	"github.com/gofiber/fiber/v2"
	"go.uber.org/zap"

	"github.com/greenmetrics/backend/internal/config"
	"github.com/greenmetrics/backend/internal/repository"
	"github.com/greenmetrics/backend/internal/services"
)

// Dependencies is the bundle of collaborators injected into handlers.
type Dependencies struct {
	Config    *config.Config
	Logger    *zap.Logger
	Repo      *repository.TimescaleRepository
	Analytics *services.EnergyAnalytics
	Carbon    *services.CarbonCalculator
	Reporter  *services.ReportGenerator
	Alerts    *services.AlertEngine
	Version   string
	Commit    string
	StartedAt time.Time
}

// Register wires all routes onto the Fiber app.
//
//	@title GreenMetrics API
//	@version 1.0
//	@description Energy monitoring + carbon accounting API. CSRD/ESRS E1 + Piano 5.0.
//	@termsOfService https://greenmetrics.it/tos
//	@contact.name GreenMetrics Support
//	@contact.email support@greenmetrics.it
//	@license.name Proprietary
//	@host localhost:8082
//	@BasePath /api
//	@securityDefinitions.apikey BearerAuth
//	@in header
//	@name Authorization
func Register(app *fiber.App, d Dependencies) {
	api := app.Group("/api")

	health := newHealthHandler(d)
	api.Get("/health", health.Check)
	api.Get("/ready", health.Ready)
	api.Get("/live", health.Live)

	// v1 endpoints. Default rate limit 60/min (v2.0 §12).
	v1 := api.Group("/v1", RateLimit(d.Config.RateLimitPerMinute))

	// CSRF for cookie-based clients; Bearer auth bypass is enabled.
	v1.Use(CSRFMiddleware(DefaultCSRFConfig(d.Config.JWTSecret)))

	auth := newAuthHandler(d)
	// Stricter limit for login (brute-force mitigation, v2.0 §12).
	v1.Post("/auth/login", RateLimit(d.Config.RateLimitLoginPerMinute), auth.Login)
	v1.Post("/auth/refresh", RateLimit(d.Config.RateLimitLoginPerMinute), auth.Refresh)
	v1.Post("/auth/logout", auth.Logout)

	// Audit middleware runs AFTER JWTMiddleware so we can attribute the row
	// to an authenticated subject.
	protected := v1.Group("", JWTMiddleware(d), AuditMiddleware(AuditConfig{Repo: d.Repo, Logger: d.Logger}))

	meters := newMetersHandler(d)
	protected.Get("/meters", meters.List)
	protected.Post("/meters", meters.Create)
	protected.Get("/meters/:id", meters.Get)
	protected.Put("/meters/:id", meters.Update)
	protected.Delete("/meters/:id", meters.Delete)
	protected.Post("/meters/:id/probe", meters.Probe)

	readings := newReadingsHandler(d)
	protected.Get("/readings", readings.Query)
	// Higher rate for ingest (v2.0 §12 suggests 300/min for ingest endpoints).
	protected.Post("/readings/ingest", RateLimit(d.Config.RateLimitIngestPerMinute), readings.Ingest)
	protected.Get("/readings/aggregated", readings.Aggregated)
	protected.Get("/readings/export", readings.Export)

	reports := newReportsHandler(d)
	protected.Get("/reports", reports.List)
	protected.Post("/reports", reports.Generate)
	protected.Get("/reports/:id", reports.Get)
	protected.Get("/reports/:id/download", reports.Download)
	protected.Post("/reports/:id/submit", reports.Submit)

	tenants := newTenantsHandler(d)
	protected.Get("/tenants/me", tenants.GetSelf)
	protected.Put("/tenants/me", tenants.UpdateSelf)

	alerts := newAlertsHandler(d)
	protected.Get("/alerts", alerts.List)
	protected.Post("/alerts/:id/ack", alerts.Ack)
	protected.Post("/alerts/:id/resolve", alerts.Resolve)

	ef := newEmissionFactorsHandler(d)
	protected.Get("/emission-factors", ef.List)
	protected.Post("/emission-factors", ef.Create)
	protected.Get("/emission-factors/:code", ef.Get)
	protected.Put("/emission-factors/:code", ef.Update)

	// Pulse-counter webhook (field gateways POST here). Validated inside the
	// handler against PULSE_WEBHOOK_SECRET; rate-limited as ingest.
	protected.Post("/pulse/ingest", RateLimit(d.Config.RateLimitIngestPerMinute), newPulseHandler(d).Ingest)

	// OpenAPI / Swagger docs. The spec is generated by `swag init`
	// into docs/openapi.json at build time; here we simply serve it.
	api.Get("/docs/openapi.json", OpenAPIHandler)
	api.Get("/docs", SwaggerUIHandler)

	// Grafana back-channel (service-to-service token).
	api.Get("/internal/metrics", MetricsHandler)
}
