apiVersion: 1

datasources:
  - name: GreenMetrics-TimescaleDB
    type: postgres
    access: proxy
    uid: greenmetrics-timescaledb
    url: greenmetrics-timescaledb:5432
    user: ${GRAFANA_DB_USER}
    database: ${GRAFANA_DB_NAME}
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
