---
apiVersion: v1
kind: Namespace
metadata:
  name: greenmetrics
  labels:
    name: greenmetrics
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: greenmetrics
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-db
  namespace: greenmetrics
spec:
  podSelector:
    matchLabels:
      app: greenmetrics
      component: backend
  policyTypes: [Egress, Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: greenmetrics
      ports:
        - protocol: TCP
          port: 8082
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432   # TimescaleDB
        - protocol: TCP
          port: 443    # ISPRA / Terna / E-Distribuzione
        - protocol: UDP
          port: 53     # DNS
