apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: greenmetrics-grafana
  namespace: greenmetrics
  annotations:
    secops.greenmetrics.it/risk: "RISK-024"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: greenmetrics-grafana-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin-user
      remoteRef:
        key: greenmetrics/prod/grafana
        property: admin_user
    - secretKey: admin-password
      remoteRef:
        key: greenmetrics/prod/grafana
        property: admin_password
