// AUTO-GENERATED by frontend/scripts/gen-branding.mjs at 2026-05-01T04:14:32.386Z.
// SOURCE: config/branding.yaml (engagement-overridable per Rule 82).
// EDIT: config/branding.yaml + run `npm run gen:branding` (or `npm run build`).
//
// Doctrine refs: Rule 80 (white-label conformance), Rule 82 (engagement overlay).
// Charter ref: §6 (white-label readiness).

export const branding = {
  "product": {
    "name": "GreenMetrics",
    "tagline": "Monitoraggio energia e reportistica regulatory-grade",
    "description": "GreenMetrics — monitoraggio energia e reportistica CSRD / Piano Transizione 5.0 per PMI manifatturiere e agroalimentari."
  },
  "vendor": {
    "name": "Macena",
    "url": "https://www.macena.it",
    "support_email": "support@example.test"
  },
  "theme": {
    "primary_color": "#166534",
    "accent_color": "#f59e0b",
    "background_color": "#fafaf9",
    "logo_path": "/logo.svg",
    "favicon_path": "/favicon.svg"
  },
  "footer": {
    "html": "© {{year}} Macena. All rights reserved.",
    "show_powered_by": true
  },
  "email": {
    "from_name": "GreenMetrics Notifications",
    "from_local_part": "noreply",
    "footer_text": "Questa email è stata generata automaticamente da GreenMetrics.\nPer assistenza scrivere a support@example.test.\n"
  },
  "regulatory": {
    "data_region": "EU/IT",
    "show_ege_signature_block": true
  }
} as const;

export type Branding = typeof branding;

export const productName = branding.product.name;
export const productTagline = branding.product.tagline;
export const productDescription = branding.product.description;
export const vendorName = branding.vendor.name;
export const supportEmail = branding.vendor.support_email;
export const primaryColor = branding.theme.primary_color;
export const accentColor = branding.theme.accent_color;
export const backgroundColor = branding.theme.background_color;
export const logoPath = branding.theme.logo_path;
export const faviconPath = branding.theme.favicon_path;
export const footerHTML = branding.footer.html.replace(/\{\{year\}\}/g, String(new Date().getFullYear()));
export const showPoweredBy = branding.footer.show_powered_by;
